package api

// Locs is a list of team locations
var Locs = []string{
	"Arizona",
	"Atlanta",
	"Baltimore",
	"Boston",
	"Chicago",
	"Chicago",
	"Cincinnati",
	"Cleveland",
	"Colorado",
	"Detroit",
	"Miami",
	"Houston",
	"Kansas City",
	"Los Angeles",
	"Los Angeles",
	"Milwaukee",
	"Minnesota",
	"New York",
	"New York",
	"Oakland",
	"Philadelphia",
	"Pittsburgh",
	"St. Louis",
	"San Diego",
	"San Francisco",
	"Seattle",
	"Tampa Bay",
	"Texas",
	"Toronto",
	"Washington",
}

// Teams is a list of team names
var Teams = []string{
	"Diamondbacks",
	"Braves",
	"Red Sox",
	"Cubs",
	"White Sox",
	"Reds",
	"Indians",
	"Rockies",
	"Tigers",
	"Marlins",
	"Astros",
	"Royals",
	"Angels",
	"Dodgers",
	"Brewers",
	"Twins",
	"Mets",
	"Yankees",
	"Athletics",
	"Phillies",
	"Pirates",
	"Cardinals",
	"Padres",
	"Giants",
	"Mariners",
	"Rays",
	"Rangers",
	"Blue Jays",
	"Nationals",
}

var TeamsWithLocs = []string{
	"Arizona Diamondbacks",
	"Atlanta Braves",
	"Boston Red Sox",
	"Chicago Cubs",
	"Chicago White Sox",
	"Cincinnati Reds",
	"Cleveland Indians",
	"Colorado Rockies",
	"Detroit Tigers",
	"Miami Marlins",
	"Houston Astros",
	"Kansas City Royals",
	"Los Angeles Angels",
	"Los Angeles Dodgers",
	"Milwaukee Brewers",
	"Minnesota Twins",
	"New York Mets",
	"New York Yankees",
	"Oakland Athletics",
	"Philadelphia Phillies",
	"Pittsburgh Pirates",
	"St. Louis Cardinals",
	"San Diego Padres",
	"San Francisco Giants",
	"Seattle Mariners",
	"Tampa Bay Rays",
	"Texas Rangers",
	"Toronto Blue Jays",
	"Washington Nationals",
}
